;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-backward-word-begin
	evil-change
	evil-forward-char
	evil-forward-word-begin
	evil-previous-line
	))

(setq mc/cmds-to-run-once
      '(
	))
